config:
  author: Joshua Soileau
  siteName: JoshuaSoileau.com
  siteDescription: My corner of the internet
  defaultPageTitle: Simple explanations of wonderful web dev techniques
  blogTitle: Blog
  baseUrl: www.joshuasoileau.com

  # For Twitter cards, this logo must be a hosted url, not a relative path.
  # Must be square. Minimum size is 144x144; maximum size 4096x4096.
  websiteLogo: "https://cdn.auth0.com/blog/logos/nextjs-logo.png"

  # if your string begins with a special character, you usually have to put it in quotes
  twitterHandle: "@joshua_soileau"
  twitterCardType: summary

  # This is list is used to create the links in the navigation panel
  navigation:
    - { text: Home, link: / }
    - { text: Experiments, link: /experiments }
    - { text: Thoughts, link: /blog }
    - { text: About, link: /about }

  css:
    primaryColor: "#536DFE"
    accentColor: "#455A64"
    lightGray: "#eeeeee"
    backgroundColor: "#ffffff"
    black: "#333"
